src/file_service/upload_file.py
src/file_service/upload_multiple_file.py

Hi @Rich627 
SCRUM-15 has been completed.
Please review, thanks

SCRUM-15 shiun post upload file

---

.github/workflows/slack_notification.yaml
.github/workflows/terraform.yaml
terraform/dev/.terraform.lock.hcl
terraform/dev/backend_setting/s3.tf
terraform/dev/cloudfront.tf
terraform/dev/main.tf
terraform/dev/output.tf
terraform/dev/route53.tf
terraform/dev/terraform.tf
terraform/dev/variables.tf
terraform/poc/backend_setting/s3.tf
terraform/poc/terraform.tf
test.txt

[TEST] Scrum 22 build a ci cd pipeline to ensure continuous delivery

---

src/auth_service/login/lambda_function.py

CORS Error Resolution for Login API
- Problem: Users encountered a "CORS origin not allowed" error during login attempts from different origins.

[SCRUM-97] Login api CORS origin not allowed error

---

src/auth_service/is_logged_in/lambda_function.py
src/auth_service/login/lambda_function.py
terraform/cloudfront_for_apis/cloudfront.tf
terraform/lambda_authorizer/lambda_authorizer/lambda_function.py

We're excited to announce some significant updates to our authentication system, designed to enhance security and streamline user experience. Here’s what’s new:
1. **Access Token Return**: The login API now returns an access token directly, simplifying the authentication process.
2. **Authorization Header Verification**: Improved security with a robust method for verifying access using the authorization header.
3. **Lambda Authorizer Enhancement**: Authentication from the authorization header is now more reliable, with fixes to ensure proper handling of lowercase headers.
4. **CloudFront Integration**: Fixed issues with CloudFront sending authorization headers to origins, ensuring consistent security practices.

[SCRUM-101] Auth login API return access token and verify access from authorization header

---

src/auth_service/terraform/dev.tfvars
src/auth_service/terraform/dynamodb.tf
src/auth_service/terraform/local-dev.tfvars
src/auth_service/terraform/preview.tfvars
src/auth_service/terraform/prod.tfvars
src/auth_service/terraform/variables.tf
src/campaign_service/terraform/dev.tfvars
src/campaign_service/terraform/dynamodb.tf
src/campaign_service/terraform/local-dev.tfvars
src/campaign_service/terraform/preview.tfvars
src/campaign_service/terraform/prod.tfvars
src/campaign_service/terraform/variables.tf
src/email_service/terraform/dev.tfvars
src/email_service/terraform/dynamodb.tf
src/email_service/terraform/local-dev.tfvars
src/email_service/terraform/preview.tfvars
src/email_service/terraform/prod.tfvars
src/email_service/terraform/variables.tf
src/file_service/terraform/dev.tfvars
src/file_service/terraform/dynamodb.tf
src/file_service/terraform/lambda.tf
src/file_service/terraform/local-dev.tfvars
src/file_service/terraform/preview.tfvars
src/file_service/terraform/prod.tfvars
src/file_service/terraform/variables.tf

1. **Accidental Deletion Protection**: Prevents unintended deletion of critical database resources.
2. **Enhanced Data Recovery**: Streamlines Point-In-Time Recovery (PITR) for improved data restoration.

[SCRUM-109] Enable deletion protection and PITR based on the environment

---

src/email_service/send_email/email_util.py
src/email_service/send_email/file_util.py
src/email_service/send_email/lambda_function.py
src/email_service/send_email/ses.py
src/email_service/send_email/template_util.py
src/email_service/terraform/lambda.tf
src/email_service/validate_input/lambda_function.py

1. **Enhanced Support for Email Fields**: 
- **Reply-To**: Easily set a reply-to address for your emails.
- **CC and BCC**: Include multiple recipients in CC and BCC fields.
- **Sender Local Part**: Customize the local part of the sender's email address.
2. **Input Validation**: 
- Ensures correct formats for CC, BCC, and Reply-To fields, reducing errors.
3. **Lambda Performance Optimizations**: 
- Increased timeout to 60 seconds and memory allocation to 512MB, ensuring robust performance even with large email batches.
4. **Utility Enhancements**: 
- Refactored functions for better modularity and maintainability.
- Added new utilities for handling email templates and file attachments.
5. **Return Format Update**: 
- Improved return format and validation to handle non-numeric and None …

[SCRUM-73]  Send email API support reply-to, bcc, cc, sender local part

---

src/email_service/terraform/dev.tfvars
src/email_service/terraform/dynamodb.tf
src/email_service/terraform/lambda.tf
src/email_service/terraform/local-dev.tfvars
src/email_service/terraform/preview.tfvars
src/email_service/terraform/prod.tfvars
src/email_service/terraform/variables.tf
src/email_service/validate_input/data_util.py
src/email_service/validate_input/lambda_function.py
src/email_service/validate_input/run_repository.py
src/email_service/validate_input/time_util.py

1. **DynamoDB Integration**: 
- Added a new DynamoDB table, "run," to log items when email requests receive a 202 Accepted response.
- Enhanced data storage for better tracking and auditing of email requests.
2. **Improved Permissions**: 
- Updated Lambda functions with the necessary permissions to ensure smooth operation.
- Integrated `data_util.py` for better handling of decimal data types.
3. **Updated Messaging**: 
- Enhanced the 202 response message for clarity and detailed status updates.

[SCRUM-108] Add item to run table if sending email request succeeds

---

src/email_service/send_email/certificate_generator.py
src/email_service/send_email/requirements.txt

**Implement:**
- Enabled font subsetting using `subset_fonts()` to reduce the embedded font size by including only used characters.
- Applied compression (`deflate=True`) during the save process to further minimize file size.
- Integrated garbage collection (`garbage=3`) to clean up unused objects and optimize the PDF structure.
- Ensured clean save (`clean=True`) to maintain the integrity and reduce the file size of the generated PDF.

[SCRUM-130] Fixed generated file being too large to be sent via email (exceeds AWS SES 10MB limit)

---

src/auth_service/change_password/lambda_function.py

This PR enhances the AWS Lambda function to handle both forced password changes for first-time logins and password resets via a verification code for users who forgot their password. The function now dynamically handles both scenarios based on the input provided.

[SCRUM-138] Dynamically handles change password based on the input provided

---

src/auth_service/change_password/lambda_function.py
src/email_service/send_email/lambda_function.py

[SCRUM-148] Redeploy email service production env

---

src/email_service/send_email/lambda_function.py
src/email_service/validate_input/lambda_function.py

Hi @chungchihhan, the work on [SCRUM-163](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-163?atlOrigin=eyJpIjoiNWI5N2FhMzdlZjc1NGY1NDlkN2Q5N2I4MTFjYjI4NDQiLCJwIjoiaiJ9) is complete.
Please review the code when you have a chance.
This enhancement expands the `POST /send-email` API to support various recipient sources, streamlining email handling and ensuring compatibility with multiple recipient configurations.
1. Added recipient_source field to specify how recipients should be provided to the backend.
- `DIRECT`: Recipient emails and template variables are provided directly in the API request body.
- `SPREADSHEET`: Recipient emails and template variables are provided via an uploaded spreadsheet file.
1. Make sure you are in the Postman `Shiun-local-dev` …

[SCRUM-163] Enhance `POST /send-email` API to support different recipient sources

---

.github/workflows/slack_notification.yaml
src/file_service/list_files/lambda_function.py

Just check that the CI/CD pipeline works well.
- [SCRUM-212](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-212)
[SCRUM-212]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SCRUM-212] file service api gateway route get files 403

---

src/webhook_service/terraform/dev.tfvars
src/webhook_service/terraform/lambda.tf
src/webhook_service/terraform/preview.tfvars
src/webhook_service/terraform/prod.tfvars

解決docker host問題在github action上面的問題
[SCRUM-214](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214)
[SCRUM-214]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scrum 214 webhook service ci cd error error pinging docker server

---

.github/workflows/webhook_service.yaml
src/webhook_service/terraform/dev.tfvars
src/webhook_service/terraform/lambda.tf
src/webhook_service/terraform/preview.tfvars
src/webhook_service/terraform/prod.tfvars
src/webhook_service/terraform/variables.tf

解決docker host問題在github action上面的問題
[SCRUM-214](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214)
[SCRUM-214]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(webhook_service): fix the error of docker not deploying with github action (SCRUM-214)

---

.github/workflows/webhook_service.yaml
src/webhook_service/save_webhook/lambda_function.py

解決docker host問題在github action上面的問題
[SCRUM-214](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214)
[SCRUM-214]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Scrum 214 webhook service ci cd error error pinging docker server new

---

src/webhook_service/save_webhook/lambda_function.py

ci(webhook_service): simply edit a word to trigger github action (SCRUM-214)

ci(webhook_service): simply edit a word to trigger github action (SCRUM-214)

---

.github/PULL_REQUEST_TEMPLATE.md

The description for this PR comes from `PULL_REQUEST_TEMPLATE.md`.
[SCRUM-226](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-226)
**GitHub Docs:** [Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[SCRUM-226]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SCRUM-226] Add pull request template

---

src/auth_service/terraform/outputs.tf
src/auth_service/terraform/secrets_manager.tf

Secrets are long-term resources. Like databases, they don’t need to be redeployed once they are deployed. For this reason, I added a `prevent_destroy = true` in `secrets_manger.tf`
[SCRUM-188](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-188)
I need to merge into the dev branch to check if the secrets will be removed.
There is a bug related to this PR: [SCRUM-255](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-225)
[SCRUM-188]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SCRUM-188] The secret of the Service Account in Secrets Manager will be gone when a new change is deployed to dev env

---

src/webhook_service/terraform/api_gateway.tf
src/webhook_service/terraform/lambda.tf
src/webhook_service/update_webhook/Dockerfile
src/webhook_service/update_webhook/lambda_function.py
src/webhook_service/update_webhook/webhook_repository.py
src/webhook_service/update_webhook/webhook_type_enum.py

Create an API for updating webhook's data.
[SCRUM-158](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-158)
For *local-dev* environment:
1. Login first -> [POST /Login](https://aws-educate-tw.postman.co/workspace/TPET-API-Development-Workspace~b6915213-64a3-408d-b297-45f472fa0a6b/request/36968695-ac08ee18-f884-4f11-979b-f3dccaaa1bf0?action=share&creator=31171060&ctx=documentation&active-environment=31171060-a68faedf-68d1-4502-9ef2-3dd830e580eb)
2. Pick a `webhook_id` from the response -> [GET /webhooks](https://aws-educate-tw.postman.co/workspace/TPET-API-Development-Workspace~b6915213-64a3-408d-b297-45f472fa0a6b/request/31171060-4a91474b-3b8c-466d-bfe8-d0666b36d9c8?action=share&creator=31171060&ctx=documentation&active-environment=31171060-a68faedf-68d1-4502-9ef2- …

Scrum 158 backend put webhooks webhook

---

src/email_service/list_runs/lambda_function.py
tests/email_service/api_regression/email_service_regression_test_collection.json

- Fixed the issue where the `GET /runs` request failed to fetch the next page of data
- Added a regression test for `GET /runs` API
- For the root cause of this bug, please refer to the comment in this [Jira issue](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-237).
[SCRUM-237](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-237)
- Call the GET /runs API in the local-dev environment to verify that the response and logic behave as expected.
[SCRUM-237]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SCRUM-237] `GET /runs` - Email history next button request failed

---

terraform/cloudfront_for_apis/terraform.tfvars

Add the path pattern for the webhook service in prod environment
[SCRUM-239](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-239)
N/A
N/A
[SCRUM-239]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(infra/cloudfront_for_apis): add the path pattern for webhook_service (SCRUM-104)

---

src/webhook_service/save_webhook/lambda_function.py
src/webhook_service/trigger_webhook/email_service.py
src/webhook_service/trigger_webhook/lambda_function.py
src/webhook_service/trigger_webhook/utils.py
src/webhook_service/trigger_webhook/webhook_handler.py
src/webhook_service/trigger_webhook/webhook_repository.py

Just like the branch name, adjust the required and optional keys in the request body.
Also, refactor the trigger-webhook service for coding guideline.
[SCRUM-244](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-244)
In `local-dev` : 
[POST /save-webhook](https://aws-educate-tw.postman.co/workspace/TPET-API-Development-Workspace~b6915213-64a3-408d-b297-45f472fa0a6b/request/31171060-fcaad98d-8b3d-43a9-9381-ff814d8af22b?action=share&creator=31171060&ctx=documentation&active-environment=31171060-53b5dd75-2d58-4c7b-8962-f9525bbda79e) 
Here is the request body, here are the required fields
- template_file_id: Identifier for the template file
- surveycake_link: URL link to the SurveyCake form
- hash_key: Cryptographic hash key for security
- iv_key: Initialization vector …

Scrum 244 backend adjust required optional

---

src/email_service/list_emails/lambda_function.py
src/email_service/send_email/Dockerfile
src/email_service/terraform/lambda.tf
src/email_service/validate_input/Dockerfile
src/email_service/validate_input/requirements.txt

This pull request introduces enhancements to the email service, including improved query parameter handling, batch processing for large data requests, and updates to infrastructure and dependencies. Key changes focus on optimizing the Lambda function for listing emails, updating Terraform configurations, and ensuring consistency in Dockerfile permissions and dependency versions.
* Added support for `limit=ALL` in `src/email_service/list_emails/lambda_function.py` to fetch all items by counting total emails and overriding pagination. Introduced batch processing for large requests to handle RDS Data API's 1MB limit. [[1]](diffhunk://#diff-9cfdbb26ee6ca087712a9fa5f44fa9bba91b39c09319e3b88c95921edd48dc47R15-R17) [[2]](diffhunk://#diff-9cfdbb26ee6ca087712a9fa5f44fa9bba91b39c09319e3b88c95921edd4 …

[SCRUM-308] Fix RDS Data API exceeds 1MB hard limits exception

---

src/webhook_service/get_webhook/lambda_function.py

This pull request introduces a minor update to the `lambda_handler` function in `src/webhook_service/get_webhook/lambda_function.py`. The change adds the `run_id` field to the response dictionary, ensuring that this value is included in the webhook details returned by the function.
[SCRUM-361](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-361)
```bash
$ curl -s --location 'https://mydomain.com/local-dev/webhooks/c43f8f5b-a431-4927-8b6c-3c03ef29921b' \
--header 'Authorization: Bearer ey' \
--header 'Cookie: acce' | jq .
{
"status": "SUCCESS",
"message": "The details of the webhook are successfully retrieved.",
"webhook_id": "c43f8f5b-a431-4927-8b6c-3c03ef29921b",
"webhook_url": "https://XXX",
"subject": "【參與證明】AWS Educate 雲端大使感謝您的參與 - local-dev - update - v6.0", …
```

[SCRUM-361] add the `run_id` field to the get webhook API response

---

src/email_service/create_email/lambda_function.py
src/email_service/validate_input/lambda_function.py
src/email_service/validate_input/recipient_source_enum.py
src/email_service/validate_input/run_repository.py
src/email_service/validate_input/run_type_enum.py

This pull request introduces major improvements to the email service's input validation and email creation Lambda functions, primarily to support a new "WEBHOOK" run type for appending recipients to existing email runs. It also enhances error handling, improves code clarity, and enforces stricter input validation for both webhook and standard email flows.
Key changes include:
**Support for "WEBHOOK" run type and recipient append mode:**
* Added logic in `validate_input/lambda_function.py` to handle a new "WEBHOOK" run type, allowing appending recipients to an existing run via direct input, with strict validation and atomic counter incrementing. The webhook logic enforces that `run_id` must be provided and that only direct recipients are allowed.
* Updated `create_email/lambda_function.py` …

[SCRUM-364] Support `WEBHOOK` run type for appending emails to existing run items

---

src/email_service/health_check/lambda_function.py
src/email_service/health_check/run_repository.py
src/email_service/health_check/time_util.py
src/email_service/send_email/lambda_function.py
src/email_service/terraform/lambda.tf
src/email_service/terraform/rds.tf

Aurora Serverless v2 requires additional time to warm up. If `/send-email` is called directly while the database is still paused, the request will fail.
- This PR completes the **`GET /health` API**, which triggers the Aurora DB instance by executing a lightweight SQL command.
- It also introduces a **retry mechanism** that performs a `/health` check to ensure the database is awake before attempting to send emails.
- In addition, this PR extends the **Aurora auto-pause timeout** to reduce the likelihood of unintended pauses during normal operations.
[SCRUM-351](https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-351)
- [] I have tested these changes.
[SCRUM-351]: https://aws-educate-cloud-ambassador-dev-team.atlassian.net/browse/SCRUM-351?atlOrigin=eyJpIjoiNWRkNTljNzYx …

[SCRUM-351] extend aurora runtime and wakeup before send-email
